<?php
require_once __DIR__ . '/../includes/config.php';
requireLogin();

$user = getCurrentUser();
$pageTitle = 'Plinko';
include __DIR__ . '/../includes/header.php';
include __DIR__ . '/../includes/navbar.php';
?>
    
    <div class="container">
        <div class="game-container section">
            <h1>⚪ Plinko</h1>
            
            <div class="plinko-game">
                <div class="bet-controls">
                    <label>Bet Amount: $</label>
                    <input type="number" id="betAmount" min="1" value="10" step="1" class="bet-input-with-adjust">
                    <small>Max: $<span id="maxBet">100</span></small>
                    <label style="margin-left: 15px;">Balls: </label>
                    <input type="number" id="ballCount" min="1" max="10" value="1" step="1" class="bet-input-with-adjust" style="width: 60px;">
                    <button id="dropBtn" class="btn btn-primary btn-large">DROP BALL(S)</button>
                </div>
                
                <div class="plinko-board-container">
                    <div class="plinko-board" id="plinkoBoard">
                        <!-- Pegs and slots will be generated by JavaScript -->
                    </div>
                    <div class="plinko-slots" id="plinkoSlots">
                        <!-- Slots will be generated by JavaScript -->
                    </div>
                </div>
                
                <div id="result" class="result-message"></div>
            </div>
            
            <div class="win-rate-section section" style="margin: 20px 0; background: #f8f9fa; border-radius: 8px;">
                <h4 style="margin: 0 0 10px 0; color: #667eea;">📊 Your Stats</h4>
                <div id="winRateDisplay" style="color: #666;">
                    <span>Win Rate: <strong id="winRate">-</strong>%</span>
                    <span style="margin-left: 20px;">Games Played: <strong id="gamesPlayed">-</strong></span>
                    <span style="margin-left: 20px;">Wins: <strong id="wins">-</strong></span>
                </div>
            </div>
            
            <div class="game-info section">
                <h3>How to Play:</h3>
                <table class="slots-info-table">
                    <tr>
                        <td>1. Set your bet amount</td>
                    </tr>
                    <tr>
                        <td>2. Click "DROP BALL" to release a ball</td>
                    </tr>
                    <tr>
                        <td>3. Watch the ball bounce down through the pegs</td>
                    </tr>
                    <tr>
                        <td>4. Win based on which slot the ball lands in!</td>
                    </tr>
                </table>
                <h4 style="margin-top: 20px; margin-bottom: 10px;">Multipliers:</h4>
                <table class="slots-payout-table" id="plinkoMultipliersTable">
                    <thead>
                        <tr>
                            <th>Slot Position</th>
                            <th>Multiplier</th>
                        </tr>
                    </thead>
                    <tbody id="plinkoMultipliersBody">
                        <tr><td colspan="2">Loading...</td></tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
    <script src="../js/plinko.js"></script>
    <script>
        $(document).ready(function() {
            // Load win rate for plinko
            $.get(getApiPath('getWinRates') + '&game=plinko', function(data) {
                if (data.success && data.winRate) {
                    $('#winRate').text(data.winRate.rate || 0);
                    $('#gamesPlayed').text(data.winRate.total || 0);
                    $('#wins').text(data.winRate.wins || 0);
                } else {
                    console.error('Failed to load stats:', data);
                    $('#winRate').text('0');
                    $('#gamesPlayed').text('0');
                    $('#wins').text('0');
                }
            }, 'json').fail(function(xhr, status, error) {
                console.error('Error loading stats:', status, error);
                $('#winRate').text('0');
                $('#gamesPlayed').text('0');
                $('#wins').text('0');
            });
            
            // Load and display multipliers
            $.get(getApiPath('getSettings'), function(data) {
                if (data.success && data.settings.plinko_multipliers && Array.isArray(data.settings.plinko_multipliers)) {
                    const multipliers = data.settings.plinko_multipliers;
                    const slotNames = ['Left Edge', 'Near Left', 'Left-Mid', 'Left-Center', 'Center', 'Right-Center', 'Right-Mid', 'Near Right', 'Right Edge'];
                    
                    let html = '';
                    for (let i = 0; i < multipliers.length; i++) {
                        html += `<tr>
                            <td>Slot ${i} (${slotNames[i]})</td>
                            <td>${multipliers[i].toFixed(1)}x</td>
                        </tr>`;
                    }
                    $('#plinkoMultipliersBody').html(html);
                }
            }, 'json');
        });
    </script>
<?php include __DIR__ . '/../includes/footer.php'; ?>
