<?php
require_once __DIR__ . '/../includes/config.php';
requireLogin();

$user = getCurrentUser();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Plinko - Casino</title>
    <link rel="stylesheet" href="../style.css">
</head>
<body>
    <nav class="navbar">
        <div class="nav-container">
            <h2>🎰 Casino</h2>
            <div class="nav-right">
                <span class="balance">Balance: $<span id="balance"><?php echo number_format($user['balance'], 2); ?></span></span>
                <a href="../index.php" class="btn btn-secondary">Home</a>
                <a href="../pages/profile.php" class="btn btn-secondary">Profile</a>
                <?php if (isAdmin()): ?>
                <a href="../pages/admin.php" class="btn btn-secondary">Admin</a>
                <?php endif; ?>
                <a href="../pages/logout.php" class="btn btn-secondary">Logout</a>
            </div>
        </div>
    </nav>
    
    <div class="container">
        <div class="game-container">
            <h1>⚪ Plinko</h1>
            
            <div class="plinko-game">
                <div class="bet-controls">
                    <label>Bet Amount: $</label>
                    <input type="number" id="betAmount" min="1" value="10" step="1">
                    <small>Max: $<span id="maxBet">100</span></small>
                    <button id="dropBtn" class="btn btn-primary btn-large">DROP BALL</button>
                </div>
                
                <div class="plinko-board-container">
                    <div class="plinko-board" id="plinkoBoard">
                        <!-- Pegs and slots will be generated by JavaScript -->
                    </div>
                    <div class="plinko-slots" id="plinkoSlots">
                        <!-- Slots will be generated by JavaScript -->
                    </div>
                </div>
                
                <div id="result" class="result-message"></div>
            </div>
            
            <div class="game-info">
                <h3>How to Play:</h3>
                <ul>
                    <li>Set your bet amount</li>
                    <li>Click "DROP BALL" to release a ball</li>
                    <li>Watch the ball bounce down through the pegs</li>
                    <li>Win based on which slot the ball lands in!</li>
                    <li>Multipliers: Left/Right edges = 0.2x, Near edges = 0.5x, Middle = 1x, Center = 2x</li>
                </ul>
            </div>
        </div>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="../js/plinko.js"></script>
</body>
</html>
