<?php
require_once __DIR__ . '/../includes/config.php';
requireLogin();

$user = getCurrentUser();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Roulette - Casino</title>
    <link rel="stylesheet" href="../style.css">
</head>
<body>
    <?php include __DIR__ . '/../includes/navbar.php'; ?>
    
    <div class="container">
        <div class="game-container">
            <h1>🎲 Roulette</h1>
            
            <div class="roulette-game">
                <div class="bet-controls">
                    <small>Max bet per number: $<span id="maxBet">100</span></small>
                </div>
                
                <div class="bet-options">
                    <h3>Place Your Bets:</h3>
                    <div class="number-bets-section">
                        <h4>Bet on specific numbers (36x payout):</h4>
                        <div class="add-number-bet">
                            <input type="number" id="numberBet" min="0" max="36" placeholder="Number (0-36)">
                            <input type="number" id="numberBetAmount" min="1" step="1" placeholder="Amount $" value="10">
                            <button id="addNumberBetBtn" class="btn btn-secondary">Add Bet</button>
                        </div>
                        <div id="activeBets" class="active-bets-list">
                            <p style="color: #666; font-style: italic;">No bets placed yet</p>
                        </div>
                        <div id="totalBetAmount" class="total-bet-display" style="display: none;">
                            <strong>Total Bet: $<span id="totalBetValue">0</span></strong>
                        </div>
                    </div>
                </div>
                
                <div class="roulette-wheel-container">
                    <div class="roulette-wheel-wrapper">
                        <div class="roulette-wheel" id="rouletteWheel">
                            <!-- Numbers will be generated by JavaScript -->
                        </div>
                        <div class="roulette-pointer"></div>
                    </div>
                    <div id="rouletteResult" class="roulette-result">Click "Spin" to play</div>
                    <button id="spinBtn" class="btn btn-primary btn-large">SPIN</button>
                </div>
                
                <div id="result" class="result-message"></div>
            </div>
            
            <div class="game-info">
                <h3>How to Play:</h3>
                <table class="slots-info-table">
                    <tr>
                        <td>1. Choose your bet type and amount</td>
                    </tr>
                    <tr>
                        <td>2. Click SPIN to play</td>
                    </tr>
                </table>
                <h4 style="margin-top: 20px; margin-bottom: 10px;">Payouts:</h4>
                <table class="slots-payout-table">
                    <thead>
                        <tr>
                            <th>Bet Type</th>
                            <th>Payout</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Red / Black / Even / Odd / Low (1-18) / High (19-36)</td>
                            <td>2x bet</td>
                        </tr>
                        <tr>
                            <td>Green (0)</td>
                            <td>14x bet</td>
                        </tr>
                        <tr>
                            <td>Specific number (0-36)</td>
                            <td>36x bet</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="../js/navbar.js"></script>
    <script src="../js/roulette.js"></script>
</body>
</html>
