<?php
require_once __DIR__ . '/../includes/config.php';
requireLogin();

$user = getCurrentUser();
$pageTitle = 'Roulette';
include __DIR__ . '/../includes/header.php';
include __DIR__ . '/../includes/navbar.php';
?>
    
    <div class="container">
        <div class="game-container section">
            <h1>🛞 Roulette</h1>
            
            <div class="roulette-game">
                <div class="roulette-wheel-container">
                    <div class="roulette-wheel-wrapper">
                        <div class="roulette-wheel" id="rouletteWheel">
                            <!-- Numbers will be generated by JavaScript -->
                        </div>
                        <div class="roulette-pointer"></div>
                    </div>
                    <div id="rouletteResult" class="roulette-result">
                        <?php 
                        $rouletteMode = getSetting('roulette_mode', 'local');
                        if ($rouletteMode === 'central') {
                            echo 'Waiting for next round...';
                        } else {
                            echo 'Click "Spin" to play';
                        }
                        ?>
                    </div>
                    <button id="spinBtn" class="btn btn-primary btn-large" style="<?php echo $rouletteMode === 'central' ? 'display: none;' : ''; ?>">SPIN</button>
                    <div id="roundCountdown" style="<?php echo $rouletteMode === 'central' ? 'display: block;' : 'display: none;'; ?> text-align: center; margin-top: 15px; font-size: 18px; color: #667eea; font-weight: bold;">
                        <div id="countdownText">Waiting for next round...</div>
                    </div>
                </div>
                
                <div class="bet-controls" style="margin-top: 30px;">
                    <small>Max bet per number: $<span id="maxBet">100</span></small>
                </div>
                
                <div class="bet-options section" style="margin-top: 20px;">
                    <h3>Place Your Bets:</h3>
                    <div class="bet-amount-control">
                        <label>Bet Amount: $</label>
                        <input type="number" id="betAmount" min="1" step="1" value="10" class="bet-input-with-adjust" style="width: 150px; padding: 8px; font-size: 16px;">
                        <small>Max: $<span id="maxBet">100</span></small>
                    </div>
                    <div class="color-bets-section">
                        <h4>Color & Range Bets (2x payout):</h4>
                        <div class="bet-buttons" style="display: flex; flex-wrap: wrap; gap: 10px; align-items: center;">
                            <button class="bet-btn" data-bet="red" data-multiplier="2">Red (2x)</button>
                            <button class="bet-btn" data-bet="black" data-multiplier="2">Black (2x)</button>
                            <button class="bet-btn" data-bet="green" data-multiplier="36">Green (36x)</button>
                            <button class="bet-btn" data-bet="even" data-multiplier="2">Even (2x)</button>
                            <button class="bet-btn" data-bet="odd" data-multiplier="2">Odd (2x)</button>
                            <button class="bet-btn" data-bet="low" data-multiplier="2">1-18 (2x)</button>
                            <button class="bet-btn" data-bet="high" data-multiplier="2">19-36 (2x)</button>
                            <div class="add-number-bet" style="margin-left: 10px; display: flex; align-items: center; gap: 5px;">
                                <input type="number" id="numberBet" min="0" max="36" placeholder="Number (0-36)" style="width: 100px; padding: 8px;">
                                <button id="addNumberBetBtn" class="btn btn-secondary" style="padding: 8px 12px;">Add Bet</button>
                            </div>
                        </div>
                        <div id="activeBets" class="active-bets-list" style="margin-top: 15px;">
                            <p>No bets placed yet</p>
                        </div>
                    </div>
                    <div id="totalBetAmount" class="total-bet-display" style="display: none; margin-top: 20px;">
                        <strong>Total Bet: $<span id="totalBetValue">0</span></strong>
                    </div>
                    <div id="bettingResult" class="betting-result-message" style="margin-top: 20px;"></div>
                </div>
                
                <?php if ($rouletteMode === 'central'): ?>
                <div class="round-info-section section" style="margin-top: 30px; border-radius: 8px; padding: 20px;">
                    <h3 style="margin-top: 0; color: #667eea; margin-bottom: 15px;">⏱️ Round Status</h3>
                    <div id="roundStatusDisplay" style="font-size: 1.1em;">
                        <div><strong>Current Round:</strong> <span id="currentRoundNumber">-</span></div>
                        <div style="margin-top: 10px;"><strong>Status:</strong> <span id="roundStatusText">Waiting...</span></div>
                        <div id="countdownDisplay" style="margin-top: 15px; font-size: 1.3em; color: #667eea; font-weight: bold;">
                            <span id="countdownValue">-</span>
                        </div>
                    </div>
                </div>
                
                <div class="round-history-section section" style="margin-top: 20px; border-radius: 8px; padding: 20px;">
                    <h3 style="margin-top: 0; color: #667eea; margin-bottom: 15px;">📋 Recent Rounds</h3>
                    <p style="margin-bottom: 10px; font-size: 0.9em; color: #666;" class="admin-description">Hover over circles to see round details</p>
                    <div id="roundHistoryList" style="min-height: 60px; padding: 10px;">
                        <p class="loading-text" style="text-align: center;">Loading history...</p>
                    </div>
                </div>
                <?php endif; ?>
                
                <div id="result" class="result-message"></div>
            </div>
            
            <div class="win-rate-section section" style="margin: 20px 0; background: #f8f9fa; border-radius: 8px;">
                <h4 style="margin: 0 0 10px 0; color: #667eea;">📊 Your Stats</h4>
                <div id="winRateDisplay" style="color: #444; font-weight: 500;">
                    <span>Win Rate: <strong id="winRate">-</strong>%</span>
                    <span style="margin-left: 20px;">Games Played: <strong id="gamesPlayed">-</strong></span>
                    <span style="margin-left: 20px;">Wins: <strong id="wins">-</strong></span>
                </div>
            </div>
            
            <div class="game-info section" style="text-align: center;">
                <button class="btn btn-secondary" onclick="openModal('rouletteHowToPlayModal')" style="margin: 5px;">How to Play</button>
                <button class="btn btn-secondary" onclick="openModal('roulettePayoutsModal')" style="margin: 5px;">Payouts</button>
            </div>
        </div>
    </div>
    
    <?php 
    $rouletteMode = getSetting('roulette_mode', 'local');
    if ($rouletteMode === 'central') {
        echo '<script src="../js/roulette.js"></script>';
    } else {
        echo '<script src="../js/roulette-local.js"></script>';
    }
    ?>
    <script>
        $(document).ready(function() {
            // Load win rate for roulette
            $.get(getApiPath('getWinRates') + '&game=roulette', function(data) {
                if (data.success && data.winRate) {
                    $('#winRate').text(data.winRate.rate || 0);
                    $('#gamesPlayed').text(data.winRate.total || 0);
                    $('#wins').text(data.winRate.wins || 0);
                } else {
                    console.error('Failed to load stats:', data);
                    $('#winRate').text('0');
                    $('#gamesPlayed').text('0');
                    $('#wins').text('0');
                }
            }, 'json').fail(function(xhr, status, error) {
                console.error('Error loading stats:', status, error);
                $('#winRate').text('0');
                $('#gamesPlayed').text('0');
                $('#wins').text('0');
            });
        });
    </script>
    
    <!-- How to Play Modal -->
    <div id="rouletteHowToPlayModal" class="modal" style="display: none;">
        <div class="modal-content">
            <span class="close" onclick="closeModal('rouletteHowToPlayModal')">&times;</span>
            <h3>How to Play:</h3>
            <table class="slots-info-table">
                <tr>
                    <td>1. Choose your bet type and amount</td>
                </tr>
                <tr>
                    <td>2. Click SPIN to play</td>
                </tr>
            </table>
        </div>
    </div>
    
    <!-- Payouts Modal -->
    <div id="roulettePayoutsModal" class="modal" style="display: none;">
        <div class="modal-content">
            <span class="close" onclick="closeModal('roulettePayoutsModal')">&times;</span>
            <h3>Payouts:</h3>
            <table class="slots-payout-table">
                <thead>
                    <tr>
                        <th>Bet Type</th>
                        <th>Payout</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Red / Black / Even / Odd / Low (1-18) / High (19-36)</td>
                        <td>2x bet</td>
                    </tr>
                    <tr>
                        <td>Green (0)</td>
                        <td>36x bet</td>
                    </tr>
                    <tr>
                        <td>Specific number (0-36)</td>
                        <td>36x bet</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
<?php include __DIR__ . '/../includes/footer.php'; ?>
