<?php
require_once __DIR__ . '/../includes/config.php';
requireLogin();

$user = getCurrentUser();
$pageTitle = 'Slots';
include __DIR__ . '/../includes/header.php';
include __DIR__ . '/../includes/navbar.php';
?>
    
    <div class="container">
        <div class="game-container section">
            <h1>🎰 Slot Machine</h1>
            
            <div class="slots-machine">
                <div class="slots-reels" id="slotsReelsContainer">
                    <!-- Reels will be dynamically generated by slots.js based on settings -->
                </div>
                
                <div class="slots-controls">
                    <div class="bet-controls">
                        <label>Bet Amount: $</label>
                        <input type="number" id="betAmount" min="1" value="10" step="1" class="bet-input-with-adjust">
                        <small>Max: $<span id="maxBet">100</span></small>
                    </div>
                    <div class="bet-rows-controls" style="margin-top: 15px;">
                        <label>Bet On:</label>
                        <select id="betRows" style="padding: 8px; border-radius: 5px; border: 2px solid #667eea; font-size: 14px; margin-left: 10px;">
                            <option value="1">1 Row (Middle)</option>
                            <option value="3">All 3 Rows</option>
                        </select>
                        <div id="totalBetDisplay" style="margin-top: 10px; padding: 10px; background: rgba(102, 126, 234, 0.1); border-radius: 5px; border: 2px solid #667eea;">
                            <strong style="color: #667eea;">Total Bet: $<span id="totalBetAmount">10.00</span></strong>
                            <small id="totalBetNote" style="display: none; color: #666; margin-left: 10px;">($<span id="baseBetAmount">10.00</span> × 3 rows)</small>
                        </div>
                    </div>
                    <button id="spinBtn" class="btn btn-primary btn-large">SPIN</button>
                </div>
                
                <div id="result" class="result-message"></div>
            </div>
            
            <div class="win-rate-section section" style="margin: 20px 0; background: #f8f9fa; border-radius: 8px;">
                <h4 style="margin: 0 0 10px 0; color: #667eea;">📊 Your Stats</h4>
                <div id="winRateDisplay" style="color: #666;">
                    <span>Win Rate: <strong id="winRate">-</strong>%</span>
                    <span style="margin-left: 20px;">Games Played: <strong id="gamesPlayed">-</strong></span>
                    <span style="margin-left: 20px;">Wins: <strong id="wins">-</strong></span>
                </div>
            </div>
            
            <div class="game-info section" style="text-align: center;">
                <button class="btn btn-secondary" onclick="openModal('slotsHowToPlayModal')" style="margin: 5px;">How to Play</button>
                <button class="btn btn-secondary" onclick="openModal('slotsPayoutsModal')" style="margin: 5px;">Payouts</button>
            </div>
        </div>
    </div>
    
    <script src="../js/slots.js"></script>
    <script>
        $(document).ready(function() {
            // Load win rate for slots
            $.get(getApiPath('getWinRates') + '&game=slots', function(data) {
                if (data.success && data.winRate) {
                    $('#winRate').text(data.winRate.rate || 0);
                    $('#gamesPlayed').text(data.winRate.total || 0);
                    $('#wins').text(data.winRate.wins || 0);
                    const netWinLoss = data.winRate.netWinLoss || 0;
                    const netWinLossText = netWinLoss >= 0 ? '$' + netWinLoss.toFixed(2) : '-$' + Math.abs(netWinLoss).toFixed(2);
                    $('#netWinLoss').text(netWinLossText).css('color', netWinLoss >= 0 ? '#28a745' : '#dc3545');
                } else {
                    console.error('Failed to load stats:', data);
                    $('#winRate').text('0');
                    $('#gamesPlayed').text('0');
                    $('#wins').text('0');
                    $('#netWinLoss').text('$0.00').css('color', '#666');
                }
            }, 'json').fail(function(xhr, status, error) {
                console.error('Error loading stats:', status, error);
                $('#winRate').text('0');
                $('#gamesPlayed').text('0');
                $('#wins').text('0');
                $('#netWinLoss').text('$0.00').css('color', '#666');
            });
        });
    </script>
    
    <!-- How to Play Modal -->
    <div id="slotsHowToPlayModal" class="modal" style="display: none;">
        <div class="modal-content">
            <span class="close" onclick="closeModal('slotsHowToPlayModal')">&times;</span>
            <h3>How to Play:</h3>
            <table class="slots-info-table">
                <tr>
                    <td>1. Set your bet amount</td>
                </tr>
                <tr>
                    <td>2. Choose to bet on 1 row (middle) or all 3 rows</td>
                </tr>
                <tr>
                    <td>3. Click SPIN to play</td>
                </tr>
                <tr>
                    <td>4. Match 3 symbols to win!</td>
                </tr>
            </table>
            <p style="margin-top: 10px; color: #666; font-size: 14px;">
                <strong>Note:</strong> Betting on all 3 rows costs 3× your bet amount, but you can win on multiple rows!
            </p>
        </div>
    </div>
    
    <!-- Payouts Modal -->
    <div id="slotsPayoutsModal" class="modal" style="display: none;">
        <div class="modal-content">
            <span class="close" onclick="closeModal('slotsPayoutsModal')">&times;</span>
            <h3>Payouts:</h3>
            <table class="slots-payout-table">
                <thead>
                    <tr>
                        <th>Symbols</th>
                        <th>Payout</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- Payouts will be dynamically loaded by slots.js -->
                    <tr><td colspan="2" style="text-align: center; color: #999;">Loading payouts...</td></tr>
                </tbody>
            </table>
        </div>
    </div>
<?php include __DIR__ . '/../includes/footer.php'; ?>
